import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { GetStaticProps } from "next";
import { IMovie } from "../busca";

interface IProps {
  info: IMovie;
}

export default function Movi({ info }: IProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>{info.title}</h1>

        <p>Nota: {info.vote_average}</p>
        <p>{info.overview}</p>

        <img
          src={`https://image.tmdb.org/t/p/original/${info.backdrop_path}`}
          width="400"
        />

        <Link href={"/busca"}>Ir para a Busca</Link>
      </main>
    </>
  );
}

export const getServerSideProps: GetStaticProps = async (context) => {
  const id = context.params?.id;

  const response = await fetch(`https://tryitoutnext.vercel.app/api/movie/${id}`);
  const json = await response.json();
  const { info } = json;

  return {
    props: {
      info,
    },
  };
};
